using System.Collections.Concurrent;
using System.Diagnostics;
using System.Runtime.InteropServices;
using SynapseMouse.App.Infrastructure;
using SynapseMouse.Core.Input;
using SynapseMouse.Core.Models;
using static SynapseMouse.App.Native.NativeMethods;

namespace SynapseMouse.App.Services;

internal enum TraceOrigin : byte
{
    /// <summary>Physical input Windows received unchanged.</summary>
    Physical,
    /// <summary>Physical input Synapse blocked (filtered or replaced).</summary>
    PhysicalBlocked,
    /// <summary>Input generated by Synapse.</summary>
    Synapse,
    /// <summary>Input injected by other software.</summary>
    OtherInjected,
}

internal enum TraceKind : byte
{
    ButtonDown,
    ButtonUp,
    Wheel,
    HWheel,
}

internal readonly record struct TraceEvent(long TimeUs, TraceKind Kind, MouseButton Button, int Delta, TraceOrigin Origin);

internal readonly record struct EngineStats(long BouncesFiltered, long DuplicatesFiltered, long DoubleClicks, long Remapped);

/// <summary>
/// Hosts the Windows input hooks and the <see cref="InputProcessor"/>.
///
/// Threads:
///  * Hook thread — owns WH_MOUSE_LL / WH_KEYBOARD_LL and pumps their messages. Callbacks only run the
///    processor and queue output, so they return within microseconds (Windows drops hooks that stall).
///  * Output thread — the only thread that calls SendInput. Delivers queued events at their due time
///    and runs debounce reconciliation. Keeping all injection on one thread preserves event order.
///
/// Hooks are installed only while something actually needs them, and are removed automatically by
/// Windows if the process exits or crashes, so mouse input can never be left blocked.
/// </summary>
internal sealed class InputEngine : IDisposable
{
    private const uint MsgUpdateHooks = WM_APP + 1;
    private const uint MsgReinstallHooks = WM_APP + 2;
    private const long EarlyToleranceUs = 150;
    private const int MaxTraceQueue = 4096;

    private readonly object _sync = new();
    private readonly InputProcessor _processor = new();
    private readonly List<OutputEvent> _hookBuffer = new(16);
    private readonly PriorityQueue<OutputEvent, (long Due, long Seq)> _queue = new();
    private readonly AutoResetEvent _wake = new(false);
    private readonly ManualResetEventSlim _hookThreadReady = new(false);
    private readonly LowLevelHookProc _mouseProc;
    private readonly LowLevelHookProc _keyboardProc;
    private readonly long _startTicks = Stopwatch.GetTimestamp();
    private readonly PreciseWaiter _waiter;

    private Thread? _hookThread;
    private Thread? _outputThread;
    private uint _hookThreadId;
    private IntPtr _mouseHook;
    private IntPtr _keyboardHook;
    private long _sequence;
    private int _inFlight;
    private bool _flushRequested;
    private double _pointerSpeedMultiplier = 1.0;
    private volatile bool _stopping;
    private volatile bool _wantMouseHook;
    private volatile bool _wantKeyboardHook;
    private volatile bool _traceEnabled;
    private volatile bool _bypass;
    private volatile bool _mouseHookActive;
    private volatile bool _keyboardHookActive;
    private long _lastMouseHookEventTicks;
    private long _physicalMoveEvents;
    private long _synapseMoveEvents;
    private ThreadPriority _priority = ThreadPriority.Highest;

    public InputEngine()
    {
        _mouseProc = MouseHookProc;
        _keyboardProc = KeyboardHookProc;
        _waiter = new PreciseWaiter(_wake);
    }

    /// <summary>Raised on the output thread for DPI/config/clutch commands.</summary>
    public event Action<ProcessorCommand>? CommandReceived;

    /// <summary>Raised (on the hook thread) when hooks are installed or removed.</summary>
    public event EventHandler? HookStateChanged;

    /// <summary>Input events for the Input Tester (filled only while tracing is enabled).</summary>
    public ConcurrentQueue<TraceEvent> Trace { get; } = new();

    public bool MouseHookActive => _mouseHookActive;

    public bool KeyboardHookActive => _keyboardHookActive;

    public bool IsRunning => _hookThread?.IsAlive == true && _outputThread?.IsAlive == true;

    public bool BypassActive => _bypass;

    public long PhysicalMoveEvents => Interlocked.Read(ref _physicalMoveEvents);

    public long SynapseMoveEvents => Interlocked.Read(ref _synapseMoveEvents);

    public long NowUs
    {
        get
        {
            long ticks = Stopwatch.GetTimestamp() - _startTicks;
            long f = Stopwatch.Frequency;
            // Split to avoid overflow; offset keeps timestamps well above zero.
            return (ticks / f * 1_000_000) + (ticks % f * 1_000_000 / f) + 1_000_000_000;
        }
    }

    /// <summary>Enables event tracing for the Input Tester (installs a monitoring hook if needed).</summary>
    public bool TraceEnabled
    {
        get => _traceEnabled;
        set
        {
            _traceEnabled = value;
            if (!value)
            {
                Trace.Clear();
            }

            RequestHookUpdate();
        }
    }

    /// <summary>
    /// When true all input passes through untouched. Used while an elevated (administrator) window is in
    /// the foreground: Windows blocks injected input into such windows, so replacing input there would
    /// make it disappear.
    /// </summary>
    public bool Bypass
    {
        get => _bypass;
        set
        {
            if (_bypass == value)
            {
                return;
            }

            _bypass = value;
            if (value)
            {
                lock (_sync)
                {
                    var buffer = new List<OutputEvent>();
                    _processor.ReleaseAll(NowUs, buffer);
                    EnqueueLocked(buffer);
                    _flushRequested = true;
                }

                _wake.Set();
            }
        }
    }

    public void Start()
    {
        _hookThread = new Thread(HookThreadMain) { IsBackground = true, Name = "Synapse input hooks", Priority = _priority };
        _hookThread.Start();
        _hookThreadReady.Wait(TimeSpan.FromSeconds(5));
        _outputThread = new Thread(OutputThreadMain) { IsBackground = true, Name = "Synapse input output", Priority = _priority };
        _outputThread.Start();
    }

    /// <summary>Applies new processor settings. Disabling releases anything held and flushes the queue.</summary>
    public void Configure(ProcessorSettings settings, double pointerSpeedMultiplier, InputThreadPriority priority, bool preciseTiming)
    {
        lock (_sync)
        {
            var buffer = new List<OutputEvent>();
            bool disabling = _processor.Settings.Enabled && !settings.Enabled;
            _processor.UpdateSettings(settings, NowUs, buffer);
            EnqueueLocked(buffer);
            if (disabling)
            {
                _flushRequested = true;
            }

            _pointerSpeedMultiplier = pointerSpeedMultiplier > 0 ? pointerSpeedMultiplier : 1.0;
            _waiter.Precise = preciseTiming;
        }

        SetPriority(priority);
        _wake.Set();
        RequestHookUpdate();
    }

    public EngineStats GetStats()
    {
        lock (_sync)
        {
            return new EngineStats(_processor.BouncesFiltered, _processor.DuplicatesFiltered, _processor.GeneratedDoubleClicks, _processor.RemappedEvents);
        }
    }

    public void ResetStats()
    {
        lock (_sync)
        {
            _processor.ResetStatistics();
        }
    }

    /// <summary>Re-installs hooks if Windows silently removed them (e.g. after a system stall).</summary>
    public void CheckHookHealth(bool cursorMovedRecently)
    {
        if (!_mouseHookActive || !cursorMovedRecently)
        {
            return;
        }

        long last = Interlocked.Read(ref _lastMouseHookEventTicks);
        if (Environment.TickCount64 - last > 4000)
        {
            Log.Warn("Mouse hook stopped receiving events; reinstalling it.");
            PostThreadMessage(_hookThreadId, MsgReinstallHooks, IntPtr.Zero, IntPtr.Zero);
        }
    }

    /// <summary>Releases held input, removes hooks and stops both threads.</summary>
    public void Shutdown()
    {
        if (_stopping)
        {
            return;
        }

        try
        {
            Configure(ProcessorSettings.Disabled, 1.0, InputThreadPriority.Normal, false);
            // Give the output thread a moment to deliver the releases.
            var deadline = Environment.TickCount64 + 500;
            while (Environment.TickCount64 < deadline)
            {
                lock (_sync)
                {
                    if (_queue.Count == 0 && _inFlight == 0)
                    {
                        break;
                    }
                }

                Thread.Sleep(5);
            }
        }
        catch (Exception ex)
        {
            Log.Error("Error while releasing input during shutdown.", ex);
        }

        _stopping = true;
        _wake.Set();
        if (_hookThreadId != 0)
        {
            PostThreadMessage(_hookThreadId, WM_QUIT, IntPtr.Zero, IntPtr.Zero);
        }

        _hookThread?.Join(1000);
        _outputThread?.Join(1000);
    }

    public void Dispose()
    {
        Shutdown();
        _waiter.Dispose();
        _wake.Dispose();
        _hookThreadReady.Dispose();
    }

    // ------------------------------------------------------------------ hook thread

    private void RequestHookUpdate()
    {
        _wantMouseHook = _processor.Settings.NeedsMouseHook || _traceEnabled;
        _wantKeyboardHook = _processor.Settings.NeedsKeyboardHook;
        if (_hookThreadId != 0)
        {
            PostThreadMessage(_hookThreadId, MsgUpdateHooks, IntPtr.Zero, IntPtr.Zero);
        }
    }

    private void HookThreadMain()
    {
        _hookThreadId = GetCurrentThreadId();
        PeekMessage(out _, IntPtr.Zero, 0, 0, PM_NOREMOVE); // create the message queue
        _hookThreadReady.Set();
        ApplyHookState();

        while (GetMessage(out MSG msg, IntPtr.Zero, 0, 0) > 0)
        {
            if (msg.message == MsgUpdateHooks)
            {
                ApplyHookState();
                continue;
            }

            if (msg.message == MsgReinstallHooks)
            {
                RemoveHooks();
                ApplyHookState();
                continue;
            }

            TranslateMessage(ref msg);
            DispatchMessage(ref msg);
        }

        RemoveHooks();
    }

    private void ApplyHookState()
    {
        bool changed = false;
        IntPtr module = GetModuleHandle(null);

        if (_wantMouseHook && _mouseHook == IntPtr.Zero)
        {
            _mouseHook = SetWindowsHookEx(WH_MOUSE_LL, _mouseProc, module, 0);
            if (_mouseHook == IntPtr.Zero)
            {
                Log.Error($"Installing the mouse hook failed (error {Marshal.GetLastWin32Error()}).");
            }

            Interlocked.Exchange(ref _lastMouseHookEventTicks, Environment.TickCount64);
            changed = true;
        }
        else if (!_wantMouseHook && _mouseHook != IntPtr.Zero)
        {
            UnhookWindowsHookEx(_mouseHook);
            _mouseHook = IntPtr.Zero;
            changed = true;
        }

        if (_wantKeyboardHook && _keyboardHook == IntPtr.Zero)
        {
            _keyboardHook = SetWindowsHookEx(WH_KEYBOARD_LL, _keyboardProc, module, 0);
            if (_keyboardHook == IntPtr.Zero)
            {
                Log.Error($"Installing the keyboard hook failed (error {Marshal.GetLastWin32Error()}).");
            }

            changed = true;
        }
        else if (!_wantKeyboardHook && _keyboardHook != IntPtr.Zero)
        {
            UnhookWindowsHookEx(_keyboardHook);
            _keyboardHook = IntPtr.Zero;
            changed = true;
        }

        _mouseHookActive = _mouseHook != IntPtr.Zero;
        _keyboardHookActive = _keyboardHook != IntPtr.Zero;
        if (changed)
        {
            HookStateChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    private void RemoveHooks()
    {
        if (_mouseHook != IntPtr.Zero)
        {
            UnhookWindowsHookEx(_mouseHook);
            _mouseHook = IntPtr.Zero;
        }

        if (_keyboardHook != IntPtr.Zero)
        {
            UnhookWindowsHookEx(_keyboardHook);
            _keyboardHook = IntPtr.Zero;
        }

        _mouseHookActive = false;
        _keyboardHookActive = false;
        HookStateChanged?.Invoke(this, EventArgs.Empty);
    }

    private unsafe IntPtr MouseHookProc(int nCode, IntPtr wParam, IntPtr lParam)
    {
        if (nCode < 0)
        {
            return CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
        }

        try
        {
            var info = (MSLLHOOKSTRUCT*)lParam;
            int msg = (int)wParam;
            Interlocked.Exchange(ref _lastMouseHookEventTicks, Environment.TickCount64);

            if ((info->flags & LLMHF_INJECTED) != 0 || IsPenOrTouch(info->dwExtraInfo))
            {
                bool ours = info->dwExtraInfo == InputInjector.Signature;
                if (msg == WM_MOUSEMOVE)
                {
                    if (ours && _traceEnabled)
                    {
                        Interlocked.Increment(ref _synapseMoveEvents);
                    }
                }
                else if (_traceEnabled)
                {
                    TraceMouse(msg, info->mouseData, ours ? TraceOrigin.Synapse : TraceOrigin.OtherInjected);
                }

                return CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
            }

            HookDecision decision = _bypass ? HookDecision.Pass : ProcessMouse(msg, info);

            if (_traceEnabled)
            {
                if (msg == WM_MOUSEMOVE)
                {
                    Interlocked.Increment(ref _physicalMoveEvents);
                }
                else
                {
                    TraceMouse(msg, info->mouseData, decision == HookDecision.Block ? TraceOrigin.PhysicalBlocked : TraceOrigin.Physical);
                }
            }

            return decision == HookDecision.Block ? (IntPtr)1 : CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
        }
        catch (Exception ex)
        {
            // Never let an exception escape into Windows; fail open (pass the event through).
            Log.Error("Mouse hook error.", ex);
            return CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
        }
    }

    private unsafe HookDecision ProcessMouse(int msg, MSLLHOOKSTRUCT* info)
    {
        HookDecision decision;
        bool queued;
        lock (_sync)
        {
            if (!_processor.Settings.Enabled)
            {
                // Monitoring only (Input Tester with Master Enable off): keep button state in sync.
                TrackOnly(msg, info->mouseData);
                return HookDecision.Pass;
            }

            long now = NowUs;
            bool allowPass = _queue.Count == 0 && _inFlight == 0;
            _hookBuffer.Clear();
            switch (msg)
            {
                case WM_MOUSEMOVE:
                    if (!_processor.WantsMovement)
                    {
                        return HookDecision.Pass;
                    }

                    // The hook reports where Windows would move the cursor; the difference from the current
                    // position is this event's movement after Windows' pointer-speed gain. Dividing by that
                    // gain recovers mouse counts, which are scaled and re-sent as relative movement.
                    GetCursorPos(out POINT cursor);
                    double k = _pointerSpeedMultiplier;
                    decision = _processor.OnMove((info->pt.X - cursor.X) / k, (info->pt.Y - cursor.Y) / k, now, _hookBuffer);
                    break;
                case WM_LBUTTONDOWN:
                    decision = _processor.OnButton(MouseButton.Left, true, now, allowPass, _hookBuffer);
                    break;
                case WM_LBUTTONUP:
                    decision = _processor.OnButton(MouseButton.Left, false, now, allowPass, _hookBuffer);
                    break;
                case WM_RBUTTONDOWN:
                    decision = _processor.OnButton(MouseButton.Right, true, now, allowPass, _hookBuffer);
                    break;
                case WM_RBUTTONUP:
                    decision = _processor.OnButton(MouseButton.Right, false, now, allowPass, _hookBuffer);
                    break;
                case WM_MBUTTONDOWN:
                    decision = _processor.OnButton(MouseButton.Middle, true, now, allowPass, _hookBuffer);
                    break;
                case WM_MBUTTONUP:
                    decision = _processor.OnButton(MouseButton.Middle, false, now, allowPass, _hookBuffer);
                    break;
                case WM_XBUTTONDOWN:
                    decision = _processor.OnButton(XButton(info->mouseData), true, now, allowPass, _hookBuffer);
                    break;
                case WM_XBUTTONUP:
                    decision = _processor.OnButton(XButton(info->mouseData), false, now, allowPass, _hookBuffer);
                    break;
                case WM_MOUSEWHEEL:
                    decision = _processor.OnWheel(false, WheelDelta(info->mouseData), now, CurrentModifiers(), allowPass, _hookBuffer);
                    break;
                case WM_MOUSEHWHEEL:
                    decision = _processor.OnWheel(true, WheelDelta(info->mouseData), now, CurrentModifiers(), allowPass, _hookBuffer);
                    break;
                default:
                    return HookDecision.Pass;
            }

            queued = EnqueueLocked(_hookBuffer);
        }

        if (queued)
        {
            _wake.Set();
        }

        return decision;
    }

    private void TrackOnly(int msg, uint mouseData)
    {
        // Feeds button edges to the (disabled) processor so its state stays accurate for when it is enabled.
        long now = NowUs;
        switch (msg)
        {
            case WM_LBUTTONDOWN or WM_LBUTTONUP:
                _processor.OnButton(MouseButton.Left, msg == WM_LBUTTONDOWN, now, true, _hookBuffer);
                break;
            case WM_RBUTTONDOWN or WM_RBUTTONUP:
                _processor.OnButton(MouseButton.Right, msg == WM_RBUTTONDOWN, now, true, _hookBuffer);
                break;
            case WM_MBUTTONDOWN or WM_MBUTTONUP:
                _processor.OnButton(MouseButton.Middle, msg == WM_MBUTTONDOWN, now, true, _hookBuffer);
                break;
            case WM_XBUTTONDOWN or WM_XBUTTONUP:
                _processor.OnButton(XButton(mouseData), msg == WM_XBUTTONDOWN, now, true, _hookBuffer);
                break;
        }

        _hookBuffer.Clear();
    }

    private unsafe IntPtr KeyboardHookProc(int nCode, IntPtr wParam, IntPtr lParam)
    {
        if (nCode < 0)
        {
            return CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
        }

        try
        {
            var info = (KBDLLHOOKSTRUCT*)lParam;
            int msg = (int)wParam;
            bool down = msg is WM_KEYDOWN or WM_SYSKEYDOWN;
            bool up = msg is WM_KEYUP or WM_SYSKEYUP;
            int vk = (int)info->vkCode;
            if ((info->flags & LLKHF_INJECTED) != 0 || _bypass || (!down && !up) || KeyNames.IsModifierKey(vk))
            {
                return CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
            }

            HookDecision decision;
            bool queued;
            lock (_sync)
            {
                _hookBuffer.Clear();
                decision = _processor.OnKey(vk, down, NowUs, CurrentModifiers(), _hookBuffer);
                queued = EnqueueLocked(_hookBuffer);
            }

            if (queued)
            {
                _wake.Set();
            }

            return decision == HookDecision.Block ? (IntPtr)1 : CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
        }
        catch (Exception ex)
        {
            Log.Error("Keyboard hook error.", ex);
            return CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
        }
    }

    // ------------------------------------------------------------------ output thread

    private void OutputThreadMain()
    {
        var batch = new List<OutputEvent>(64);
        var tickBuffer = new List<OutputEvent>(8);
        var inputs = new List<OutputEvent>(64);

        while (!_stopping)
        {
            long waitUs;
            lock (_sync)
            {
                long now = NowUs;
                tickBuffer.Clear();
                _processor.Tick(now, tickBuffer);
                EnqueueLocked(tickBuffer);

                batch.Clear();
                bool flush = _flushRequested;
                _flushRequested = false;
                while (_queue.TryPeek(out var head, out _) && (flush || head.DueUs <= now + EarlyToleranceUs))
                {
                    batch.Add(_queue.Dequeue());
                }

                _inFlight = batch.Count;
                long next = _queue.TryPeek(out var nextEvent, out _) ? nextEvent.DueUs : long.MaxValue;
                next = Math.Min(next, _processor.NextTickUs);
                waitUs = next == long.MaxValue ? -1 : Math.Max(0, next - now);
            }

            if (batch.Count > 0)
            {
                Deliver(batch, inputs);
                lock (_sync)
                {
                    _inFlight = 0;
                }

                continue;
            }

            try
            {
                _waiter.Wait(waitUs);
            }
            catch (ObjectDisposedException)
            {
                return;
            }
        }
    }

    private void Deliver(List<OutputEvent> batch, List<OutputEvent> inputs)
    {
        inputs.Clear();
        foreach (var e in batch)
        {
            if (e.IsInput)
            {
                inputs.Add(e);
                continue;
            }

            // Keep ordering: send pending input before handling a command.
            SafeSend(inputs);
            inputs.Clear();
            if (e.Command == ProcessorCommand.MaskModifierKey)
            {
                InputInjector.SendMaskKey();
            }
            else
            {
                try
                {
                    CommandReceived?.Invoke(e.Command);
                }
                catch (Exception ex)
                {
                    Log.Error("Command handler failed.", ex);
                }
            }
        }

        SafeSend(inputs);
    }

    private static void SafeSend(List<OutputEvent> inputs)
    {
        if (inputs.Count == 0)
        {
            return;
        }

        try
        {
            InputInjector.Send(inputs);
        }
        catch (Exception ex)
        {
            Log.Error("SendInput failed.", ex);
        }
    }

    // ------------------------------------------------------------------ helpers

    /// <summary>Must be called with <see cref="_sync"/> held. Returns true when events were queued.</summary>
    private bool EnqueueLocked(List<OutputEvent> events)
    {
        if (events.Count == 0)
        {
            return false;
        }

        foreach (var e in events)
        {
            _queue.Enqueue(e, (e.DueUs, _sequence++));
        }

        return true;
    }

    private void SetPriority(InputThreadPriority priority)
    {
        var p = priority switch
        {
            InputThreadPriority.Normal => ThreadPriority.Normal,
            InputThreadPriority.AboveNormal => ThreadPriority.AboveNormal,
            _ => ThreadPriority.Highest,
        };
        if (p == _priority)
        {
            return;
        }

        _priority = p;
        try
        {
            if (_hookThread is { IsAlive: true })
            {
                _hookThread.Priority = p;
            }

            if (_outputThread is { IsAlive: true })
            {
                _outputThread.Priority = p;
            }
        }
        catch (ThreadStateException)
        {
            // Thread finished.
        }
    }

    private void TraceMouse(int msg, uint mouseData, TraceOrigin origin)
    {
        if (Trace.Count > MaxTraceQueue)
        {
            return;
        }

        long now = NowUs;
        TraceEvent? e = msg switch
        {
            WM_LBUTTONDOWN => new TraceEvent(now, TraceKind.ButtonDown, MouseButton.Left, 0, origin),
            WM_LBUTTONUP => new TraceEvent(now, TraceKind.ButtonUp, MouseButton.Left, 0, origin),
            WM_RBUTTONDOWN => new TraceEvent(now, TraceKind.ButtonDown, MouseButton.Right, 0, origin),
            WM_RBUTTONUP => new TraceEvent(now, TraceKind.ButtonUp, MouseButton.Right, 0, origin),
            WM_MBUTTONDOWN => new TraceEvent(now, TraceKind.ButtonDown, MouseButton.Middle, 0, origin),
            WM_MBUTTONUP => new TraceEvent(now, TraceKind.ButtonUp, MouseButton.Middle, 0, origin),
            WM_XBUTTONDOWN => new TraceEvent(now, TraceKind.ButtonDown, XButton(mouseData), 0, origin),
            WM_XBUTTONUP => new TraceEvent(now, TraceKind.ButtonUp, XButton(mouseData), 0, origin),
            WM_MOUSEWHEEL => new TraceEvent(now, TraceKind.Wheel, default, WheelDelta(mouseData), origin),
            WM_MOUSEHWHEEL => new TraceEvent(now, TraceKind.HWheel, default, WheelDelta(mouseData), origin),
            _ => null,
        };
        if (e.HasValue)
        {
            Trace.Enqueue(e.Value);
        }
    }

    private static MouseButton XButton(uint mouseData) =>
        ((mouseData >> 16) & 0xFFFF) == XBUTTON2 ? MouseButton.XButton2 : MouseButton.XButton1;

    private static int WheelDelta(uint mouseData) => (short)((mouseData >> 16) & 0xFFFF);

    /// <summary>Pen and touch generate promoted mouse messages tagged with this signature.</summary>
    private static bool IsPenOrTouch(UIntPtr extraInfo) => ((ulong)extraInfo & 0xFFFFFF00) == 0xFF515700;

    private static KeyModifiers CurrentModifiers()
    {
        var m = KeyModifiers.None;
        if (IsKeyDown(KeyNames.VkControl))
        {
            m |= KeyModifiers.Ctrl;
        }

        if (IsKeyDown(KeyNames.VkShift))
        {
            m |= KeyModifiers.Shift;
        }

        if (IsKeyDown(KeyNames.VkMenu))
        {
            m |= KeyModifiers.Alt;
        }

        if (IsKeyDown(KeyNames.VkLWin) || IsKeyDown(KeyNames.VkRWin))
        {
            m |= KeyModifiers.Win;
        }

        return m;
    }
}
